### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by patcito** [react-europe/react-europe-2018-mobile#1]
- [x] fix layout when more than one speaker #2 
- [x] open speaker screen when click on a speaker in talk details page #3
- [x] open twitter account inc Crew section when click on a crew member #4
- [ ] use urql to use the endpoint in async mode (this one's probably for @brentvatne) #5
- [x] allow user to scan their ticket QR code #6

**Comment by aehp20** [comment]
Ok pour moi!

2018-03-18 11:34 GMT+01:00 Patrick Aljord <notifications@github.com>:

**Comment by brentvatne** [comment]
cool yeah i can look at #5 soonish
